import mongoose from 'mongoose'
import dotenv from 'dotenv'
import color from 'colors'
import users from './data/users.js'
import products from './data/products.js'
import User from './models/userModel'
import Product from './models/productModel'
import Order from './models/userModel'