const product = [
    {
        _id: '1',
        name: 'Iphone 11 64GB',
        image: '/images/iphone.jpg',
        description: 'Iphone 11 nè',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '2',
        name: 'Iphone 11 64GB',
        image: '/images/iphone.jpg',
        description: 'Iphone 11 nè',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '3',
        name: 'Iphone 11 64GB',
        image: '/images/iphone.jpg',
        description: 'Iphone 11 nè',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '4',
        name: 'Iphone 11 64GB',
        image: '/images/iphone.jpg',
        description: 'Iphone 11 nè',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '5',
        name: 'Iphone 11 64GB',
        image: '/images/iphone.jpg',
        description: 'Iphone 11 nè',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '1',
        name: 'Iphone 11 64GB',
        image: '/images/iphone.jpg',
        description: 'Iphone 11 nè',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
]

export default product