const product = [
    {
        _id: '1',
        name: 'Iphone 11 64GB',
        image: '/images/iphone.jpg',
        description: 'Iphone 11 nè',
        brand: 'Apple',
        category: 'Electronics',
        price: 75.00,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '2',
        name: 'Iphone 12 Pro Max 128GB',
        image: '/images/iphone2.jpg',
        description: 'Iphone 12 Pro Max nè',
        brand: 'Apple',
        category: 'Electronics',
        price: 1500.00,
        countInStock: 9,
        rating: 5,
        numReviews: 6,
    },
    {
        _id: '3',
        name: 'Samsung Galaxy Z Flip3 5G',
        image: '/images/samsung.jpg',
        description: 'Samsung Samsung Galaxy Z Flip3 5G nè',
        brand: 'Samsung',
        category: 'Electronics',
        price: 1200.00,
        countInStock: 7,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '4',
        name: 'Samsung Galaxy Note 20',
        image: '/images/samsung2.jpg',
        description: 'Samsung Galaxy Note 20 nè',
        brand: 'Samsung',
        category: 'Electronics',
        price: 75.00,
        countInStock: 5,
        rating: 4.5,
        numReviews: 35,
    },
    {
        _id: '5',
        name: 'Oppo Reno6 5G',
        image: '/images/oppo.jpg',
        description: 'Oppo Reno6 5G nè',
        brand: 'Oppo',
        category: 'Electronics',
        price: 60.00,
        countInStock: 7,
        rating: 3.5,
        numReviews: 15,
    },
    {
        _id: '6',
        name: 'Vivo V21 5G',
        image: '/images/vivo.jpg',
        description: 'Vivo V21 5G nè',
        brand: 'Vivo',
        category: 'Electronics',
        price: 89.99,
        countInStock: 10,
        rating: 4,
        numReviews: 10,
    },
]

export default product