export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT__REQUEST = 'PRODUCT__REQUEST'
export const PRODUCT__SUCCESS = 'PRODUCT__SUCCESS'
export const PRODUCT__FAIL = 'PRODUCT__FAIL'