export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER__REQUEST = 'USER__REQUEST'
export const USER__SUCCESS = 'USER__SUCCESS'
export const USER__FAIL = 'USER__FAIL'